swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger REST Article
consumes:
  - "application/json"
produces:
  - "application/json"

basePath: "/api"

# Paths supported by the server application
paths:
  /search:
    get:
      operationId: "sources.search"
      parameters: 
        - in: query
          name: title
          required: true
          type: string
        - in: query
          name: numberOfResults
          required: false
          type: integer
          default: 10
      tags:
        - "Search"
      summary: "Endpoing will call web crawler that finds different news sources from Google"
      description: "Get a list of different news sources"
      responses:
        200:
          description: "Successfully found different news sources for a given article"
          schema:
            type: array
            items:
              properties:
                url: 
                  type: "string"
                title: 
                  type: "string"
                source:
                  type: "string"